version: '3'

services:
  weather-xm:
    depends_on:
      - mongodb
#    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://weatherXMDocker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: weatherXMDocker
    env_file:
      - .env.docker
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - weather-xm

volumes:
  mongodata:

