version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env.docker
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  weather-xm-api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env.docker
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: