version: '3'

services:
  weather-xm:
    container_name: weather-xm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env.docker:/app/.env.docker
      - ./:/app
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: weather-xm

